#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Running pre-commit checks..."
yarn lint-staged
if [ $? -ne 0 ]; then
  echo "❌ Linting or formatting failed. Commit aborted."
  exit 1
fi

echo "✅ Pre-commit checks passed."
